# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c7357db96c656961cee77d51ee1cbded2f8c8dd1af6c1f17d7564f1e6a78c8ccb7da9f8449bd4007e2c7c15b6186424df08fc425f0ed4390665cd94e6b2f8baf

test:
  secret_key_base: 803c2edbdb4c80fefa18ff8e8a88de84689345146063521d4b45c3fa04b2f37a699ef3fd73c18a7d2ffe337a43fc9be2aab617181db11af09019381c464d2978

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
